version: '3'
services:
  #Database MySql
  db:
    image: a20687/db:latest
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite  
  #WordPress CMS
  wordpress:
    depends_on:
      - db
    image: a20687/wordpress:latest
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - '8000:80'
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
